//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LINK { get; set; }
        public int ID_Users { get; set; }
        public string NOTE { get; set; }
    
        public virtual User User { get; set; }
    }
}
